name: mandi
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0+20260212

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  appwrite: ^17.1.0
  get_it: ^9.2.0
  go_router: ^16.1.0
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.1
  gap: ^3.0.1
  multi_listenable: ^0.9.3
  slang: ^4.12.1
  slang_flutter: ^4.12.1
  slang_build_runner: ^4.12.1
  build_runner: ^2.4.15
  another_flushbar: ^1.12.32
  image: ^4.7.2
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/
